### PR TITLE
Add a note baout psycopg2

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by fijal** [comment]
do you mind providing a link for that?

**Comment by alex** [comment]
A link to PyPI, or somethign else?

**Comment by fijal** [comment]
yes, pypi would do, sorry I thought replying to mail would work (it didn't)

**Comment by alex** [comment]
It usually does, I'm sure it depends on precise formatting details.

On Tue, Dec 22, 2015 at 12:59 PM, Maciej Fijalkowski <
notifications@github.com> wrote:

> yes, pypi would do, sorry I thought replying to mail would work (it didn't)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/baroquesoftware/pypy.packages/pull/4#issuecomment-166691070
> .

## 

"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by alex** [comment]
@fijal done

**Pull request merged**
